// NPC interaction router. Endpoints here are per-user and require auth.
//
//   POST /api/npc/:npcId/interact   submit a free-text dialog message,
//                                   get the NPC's reply line for *this*
//                                   player. Reply is generated by the
//                                   Gemini key pool when keys exist; on
//                                   any AI failure we fall back to the
//                                   static dialog library so the world
//                                   stays playable.
//
//   GET  /api/npc/:npcId/history    list this player's recent dialog
//                                   turns with the given NPC.
//
// The world event log (kernel events) is NOT touched here — player NPC
// dialog is intentionally a private slice. Public events (NPC routine
// moves, weather, rare windows) keep flowing through SimulationRuntime.

import { Router, type Request, type Response } from 'express'
import type { SimulationRuntime } from '../sim/runtime.js'
import { requireAuth, type AuthConfig } from './auth.js'
import {
  RELATIONSHIP_MAX,
  RELATIONSHIP_MIN,
  type PlayerStateStore,
  clampTrust,
} from './playerState.js'
import {
  INTERACT_INTENTS,
  isInteractIntent,
  pickLine,
  tierForRelationship,
  type InteractIntent,
  type RelationshipTier,
} from '../npcs/dialog.js'
import { generateAiReply, AiDialogError } from '../npcs/aiDialog.js'
import type { SettingsStore } from './settings.js'
import { TICKS_PER_HOUR } from '../config/world.js'

const HISTORY_DEFAULT_LIMIT = 20
const HISTORY_MAX_LIMIT = 100
const PLAYER_MESSAGE_MAX_CHARS = 800

// greet 冷卻：每位玩家對每個 NPC 在這個 tick 視窗內最多 +1，避免連點 quick intent 灌好感
const GREET_COOLDOWN_TICKS = TICKS_PER_HOUR
// AI 回傳的 trustDelta 在 server side 再 clamp 一次：上界 +2，避免 AI 隨意給 +3
const AI_TRUST_DELTA_MAX = 2
const AI_TRUST_DELTA_MIN = -5

type ReplySource = 'ai' | 'fallback'

export function createNpcRouter(input: {
  runtime: SimulationRuntime
  store: PlayerStateStore
  settings: SettingsStore
  authConfig: AuthConfig
}): Router {
  const router = Router()
  const auth = requireAuth(input.authConfig)

  router.post('/npc/:npcId/interact', auth, async (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND', message: `Unknown NPC id: ${npcId}` })
      return
    }
    const body = (req.body ?? {}) as { message?: unknown; intent?: unknown }
    const message = readMessage(body.message)
    const explicitIntent = isInteractIntent(body.intent) ? body.intent : null
    if (!message && !explicitIntent) {
      res.status(400).json({
        error: 'EMPTY_INPUT',
        message: '請輸入要對 NPC 說的話（或選擇一個動作）。',
      })
      return
    }
    if (message && message.length > PLAYER_MESSAGE_MAX_CHARS) {
      res.status(400).json({
        error: 'MESSAGE_TOO_LONG',
        message: `訊息不可超過 ${PLAYER_MESSAGE_MAX_CHARS} 字。`,
      })
      return
    }

    const tick = input.runtime.getCurrentTick()
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const existing = input.store.getRelation(claims.sub, npcId)
    const previousTrust = existing ? existing.trust : baseTrust
    const previousCount = existing ? existing.interactionCount : 0

    const history = input.store.listPersonalEvents({
      accountId: claims.sub,
      npcId,
      limit: 10,
    })

    const tier: RelationshipTier = tierForRelationship(previousTrust)
    const playerMessage = message ?? fallbackMessageFor(explicitIntent!)

    let replySource: ReplySource = 'fallback'
    let replyZh = ''
    let replyEn = ''
    let resolvedIntent: InteractIntent = explicitIntent ?? 'ask'
    let aiTrustDelta: number | null = null
    let aiError: string | null = null

    const hasKeys = input.settings.countActive() > 0
    if (hasKeys) {
      try {
        const ai = await generateAiReply(input.settings, {
          profile,
          trust: previousTrust,
          tier,
          history,
          playerMessage,
          worldTick: tick,
        })
        replyZh = ai.zh
        replyEn = ai.en
        resolvedIntent = explicitIntent ?? ai.intent
        aiTrustDelta = ai.trustDelta
        replySource = 'ai'
      } catch (err) {
        aiError = err instanceof AiDialogError ? err.message : String(err)
        console.warn('[npc] AI dialog failed, using fallback', aiError)
      }
    }

    if (replySource === 'fallback') {
      const intent = resolvedIntent
      const rotationSeed = tick + Math.floor(previousTrust) + previousCount
      const line = pickLine(npcId, intent, tier, rotationSeed)
      replyZh = line.zh
      replyEn = line.en
      aiTrustDelta = staticTrustDelta(intent, previousTrust, profile, {
        tick,
        lastInteractionTick: existing?.lastInteractionTick ?? 0,
        interactionCount: previousCount,
      })
    } else if (aiTrustDelta !== null) {
      // AI 回傳的值再做一次伺服器端 clamp：上限收緊，避免 AI 連續給高分把好感拉滿
      aiTrustDelta = serverClampAiDelta(aiTrustDelta, {
        intent: resolvedIntent,
        playerMessage,
        tick,
        lastInteractionTick: existing?.lastInteractionTick ?? 0,
      })
    }

    const trustAfter = clampTrust(previousTrust + (aiTrustDelta ?? 0))
    const newTier = tierForRelationship(trustAfter)

    const relation = input.store.upsertRelation({
      accountId: claims.sub,
      npcId,
      trust: trustAfter,
      interactionCount: previousCount + 1,
      lastInteractionTick: tick,
    })

    const personalEvent = input.store.appendPersonalEvent({
      accountId: claims.sub,
      npcId,
      intent: resolvedIntent,
      lineZh: replyZh,
      lineEn: replyEn,
      tick,
      trustAfter: relation.trust,
    })

    res.json({
      npcId,
      intent: resolvedIntent,
      tick,
      line: { zh: replyZh, en: replyEn },
      replySource,
      aiError: replySource === 'fallback' ? aiError : null,
      relationship: {
        trust: relation.trust,
        previousTrust,
        delta: relation.trust - previousTrust,
        tier: newTier,
        interactionCount: relation.interactionCount,
        min: RELATIONSHIP_MIN,
        max: RELATIONSHIP_MAX,
      },
      personalEvent: {
        id: personalEvent.id,
        occurredAt: new Date(personalEvent.occurredAt).toISOString(),
        intent: personalEvent.intent,
      },
    })
  })

  router.get('/npc/:npcId/history', auth, (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND' })
      return
    }
    const limit = clampInt(req.query.limit, 1, HISTORY_MAX_LIMIT, HISTORY_DEFAULT_LIMIT)
    const rows = input.store.listPersonalEvents({
      accountId: claims.sub,
      npcId,
      limit,
    })
    const relation = input.store.getRelation(claims.sub, npcId)
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const trust = relation ? relation.trust : baseTrust
    res.json({
      npcId,
      relationship: {
        trust,
        tier: tierForRelationship(trust),
        interactionCount: relation ? relation.interactionCount : 0,
        lastInteractionTick: relation ? relation.lastInteractionTick : 0,
        min: RELATIONSHIP_MIN,
        max: RELATIONSHIP_MAX,
        seeded: relation === null,
      },
      events: rows.map((row) => ({
        id: row.id,
        intent: row.intent,
        line: { zh: row.lineZh, en: row.lineEn },
        tick: row.tick,
        occurredAt: new Date(row.occurredAt).toISOString(),
        trustAfter: row.trustAfter,
      })),
    })
  })

  return router
}

function readMessage(raw: unknown): string | null {
  if (typeof raw !== 'string') return null
  const trimmed = raw.trim()
  return trimmed.length > 0 ? trimmed : null
}

function fallbackMessageFor(intent: InteractIntent): string {
  switch (intent) {
    case 'greet':
      return '（玩家走上前打招呼。）'
    case 'ask':
      return '（玩家想探聽近況。）'
    case 'trade':
      return '（玩家提議一筆交易。）'
    case 'leave':
      return '（玩家準備告辭。）'
  }
}

function staticTrustDelta(
  intent: InteractIntent,
  previous: number,
  profile: { personality: Readonly<Record<string, number | string>> },
  ctx: { tick: number; lastInteractionTick: number; interactionCount: number }
): number {
  // greet 在 fallback 路徑加 cooldown：每位 NPC 每 GREET_COOLDOWN_TICKS 內最多 +1
  if (intent === 'greet') {
    const sinceLast = ctx.tick - ctx.lastInteractionTick
    const isFirstEver = ctx.interactionCount === 0
    const cooldownPassed = sinceLast >= GREET_COOLDOWN_TICKS
    if (!isFirstEver && !cooldownPassed) return 0
    const patience =
      typeof profile.personality.patience === 'number' ? profile.personality.patience : 0.5
    if (patience < 0.3) return 0
    return 1
  }
  // ask / trade 在 fallback 路徑（沒有實際資訊或物品交換）回 0；
  // 之後 trade 接到實際物品交換時，再用 trade 撮合結果額外加分
  if (intent === 'trade' && previous < 30) return -1
  return 0
}

/**
 * AI 回傳的 trustDelta 在伺服器端再做收緊：
 * - 上限：+2（AI 不可單次給 +3）
 * - greet 額外套 cooldown：1 小時內最多 +1
 * - 短訊息（< 4 字）忽略 +N，最多 +0
 * - 下界保留 -5 給嚴重冒犯
 */
function serverClampAiDelta(
  raw: number,
  ctx: {
    intent: InteractIntent
    playerMessage: string
    tick: number
    lastInteractionTick: number
  }
): number {
  let v = Math.round(raw)
  if (v > AI_TRUST_DELTA_MAX) v = AI_TRUST_DELTA_MAX
  if (v < AI_TRUST_DELTA_MIN) v = AI_TRUST_DELTA_MIN
  if (ctx.intent === 'greet' && v > 0) {
    const sinceLast = ctx.tick - ctx.lastInteractionTick
    if (sinceLast < GREET_COOLDOWN_TICKS) v = 0
    else if (v > 1) v = 1
  }
  if (v > 0 && ctx.playerMessage.trim().length < 4) {
    // 太短的訊息（例如「嗯」「喔」）視為無實質互動
    v = 0
  }
  return v
}

function clampInt(raw: unknown, min: number, max: number, fallback: number): number {
  const n = typeof raw === 'string' ? Number.parseInt(raw, 10) : NaN
  if (!Number.isFinite(n)) return fallback
  return Math.max(min, Math.min(max, n))
}

export const _SUPPORTED_INTENTS = INTERACT_INTENTS
