// NPC interaction router. Endpoints here are per-user and require auth.
//
//   POST /api/npc/:npcId/interact   submit a free-text dialog message,
//                                   get the NPC's reply line for *this*
//                                   player. Reply is generated by the
//                                   Gemini key pool when keys exist; on
//                                   any AI failure we fall back to the
//                                   static dialog library so the world
//                                   stays playable.
//
//   GET  /api/npc/:npcId/history    list this player's recent dialog
//                                   turns with the given NPC.
//
// The world event log (kernel events) is NOT touched here — player NPC
// dialog is intentionally a private slice. Public events (NPC routine
// moves, weather, rare windows) keep flowing through SimulationRuntime.

import { Router, type Request, type Response } from 'express'
import type { SimulationRuntime } from '../sim/runtime.js'
import { requireAuth, type AuthConfig } from './auth.js'
import {
  RELATIONSHIP_MAX,
  RELATIONSHIP_MIN,
  type PlayerStateStore,
  clampTrust,
} from './playerState.js'
import {
  INTERACT_INTENTS,
  isInteractIntent,
  pickLine,
  tierForRelationship,
  type InteractIntent,
  type RelationshipTier,
} from '../npcs/dialog.js'
import { generateAiReply, AiDialogError } from '../npcs/aiDialog.js'
import type { SettingsStore } from './settings.js'

const HISTORY_DEFAULT_LIMIT = 20
const HISTORY_MAX_LIMIT = 100
const PLAYER_MESSAGE_MAX_CHARS = 800

type ReplySource = 'ai' | 'fallback'

export function createNpcRouter(input: {
  runtime: SimulationRuntime
  store: PlayerStateStore
  settings: SettingsStore
  authConfig: AuthConfig
}): Router {
  const router = Router()
  const auth = requireAuth(input.authConfig)

  router.post('/npc/:npcId/interact', auth, async (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND', message: `Unknown NPC id: ${npcId}` })
      return
    }
    const body = (req.body ?? {}) as { message?: unknown; intent?: unknown }
    const message = readMessage(body.message)
    const explicitIntent = isInteractIntent(body.intent) ? body.intent : null
    if (!message && !explicitIntent) {
      res.status(400).json({
        error: 'EMPTY_INPUT',
        message: '請輸入要對 NPC 說的話（或選擇一個動作）。',
      })
      return
    }
    if (message && message.length > PLAYER_MESSAGE_MAX_CHARS) {
      res.status(400).json({
        error: 'MESSAGE_TOO_LONG',
        message: `訊息不可超過 ${PLAYER_MESSAGE_MAX_CHARS} 字。`,
      })
      return
    }

    const tick = input.runtime.getCurrentTick()
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const existing = input.store.getRelation(claims.sub, npcId)
    const previousTrust = existing ? existing.trust : baseTrust
    const previousCount = existing ? existing.interactionCount : 0

    const history = input.store.listPersonalEvents({
      accountId: claims.sub,
      npcId,
      limit: 10,
    })

    const tier: RelationshipTier = tierForRelationship(previousTrust)
    const playerMessage = message ?? fallbackMessageFor(explicitIntent!)

    let replySource: ReplySource = 'fallback'
    let replyZh = ''
    let replyEn = ''
    let resolvedIntent: InteractIntent = explicitIntent ?? 'ask'
    let aiTrustDelta: number | null = null
    let aiError: string | null = null

    const hasKeys = input.settings.countActive() > 0
    if (hasKeys) {
      try {
        const ai = await generateAiReply(input.settings, {
          profile,
          trust: previousTrust,
          tier,
          history,
          playerMessage,
          worldTick: tick,
        })
        replyZh = ai.zh
        replyEn = ai.en
        resolvedIntent = explicitIntent ?? ai.intent
        aiTrustDelta = ai.trustDelta
        replySource = 'ai'
      } catch (err) {
        aiError = err instanceof AiDialogError ? err.message : String(err)
        console.warn('[npc] AI dialog failed, using fallback', aiError)
      }
    }

    if (replySource === 'fallback') {
      const intent = resolvedIntent
      const rotationSeed = tick + Math.floor(previousTrust) + previousCount
      const line = pickLine(npcId, intent, tier, rotationSeed)
      replyZh = line.zh
      replyEn = line.en
      aiTrustDelta = staticTrustDelta(intent, previousTrust, profile)
    }

    const trustAfter = clampTrust(previousTrust + (aiTrustDelta ?? 0))
    const newTier = tierForRelationship(trustAfter)

    const relation = input.store.upsertRelation({
      accountId: claims.sub,
      npcId,
      trust: trustAfter,
      interactionCount: previousCount + 1,
      lastInteractionTick: tick,
    })

    const personalEvent = input.store.appendPersonalEvent({
      accountId: claims.sub,
      npcId,
      intent: resolvedIntent,
      lineZh: replyZh,
      lineEn: replyEn,
      tick,
      trustAfter: relation.trust,
    })

    res.json({
      npcId,
      intent: resolvedIntent,
      tick,
      line: { zh: replyZh, en: replyEn },
      replySource,
      aiError: replySource === 'fallback' ? aiError : null,
      relationship: {
        trust: relation.trust,
        previousTrust,
        delta: relation.trust - previousTrust,
        tier: newTier,
        interactionCount: relation.interactionCount,
        min: RELATIONSHIP_MIN,
        max: RELATIONSHIP_MAX,
      },
      personalEvent: {
        id: personalEvent.id,
        occurredAt: new Date(personalEvent.occurredAt).toISOString(),
        intent: personalEvent.intent,
      },
    })
  })

  router.get('/npc/:npcId/history', auth, (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND' })
      return
    }
    const limit = clampInt(req.query.limit, 1, HISTORY_MAX_LIMIT, HISTORY_DEFAULT_LIMIT)
    const rows = input.store.listPersonalEvents({
      accountId: claims.sub,
      npcId,
      limit,
    })
    const relation = input.store.getRelation(claims.sub, npcId)
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const trust = relation ? relation.trust : baseTrust
    res.json({
      npcId,
      relationship: {
        trust,
        tier: tierForRelationship(trust),
        interactionCount: relation ? relation.interactionCount : 0,
        lastInteractionTick: relation ? relation.lastInteractionTick : 0,
        min: RELATIONSHIP_MIN,
        max: RELATIONSHIP_MAX,
        seeded: relation === null,
      },
      events: rows.map((row) => ({
        id: row.id,
        intent: row.intent,
        line: { zh: row.lineZh, en: row.lineEn },
        tick: row.tick,
        occurredAt: new Date(row.occurredAt).toISOString(),
        trustAfter: row.trustAfter,
      })),
    })
  })

  return router
}

function readMessage(raw: unknown): string | null {
  if (typeof raw !== 'string') return null
  const trimmed = raw.trim()
  return trimmed.length > 0 ? trimmed : null
}

function fallbackMessageFor(intent: InteractIntent): string {
  switch (intent) {
    case 'greet':
      return '（玩家走上前打招呼。）'
    case 'ask':
      return '（玩家想探聽近況。）'
    case 'trade':
      return '（玩家提議一筆交易。）'
    case 'leave':
      return '（玩家準備告辭。）'
  }
}

function staticTrustDelta(
  intent: InteractIntent,
  previous: number,
  profile: { personality: Readonly<Record<string, number | string>> }
): number {
  const base: Record<InteractIntent, number> = {
    greet: 1,
    ask: 0,
    trade: 0,
    leave: 0,
  }
  let delta = base[intent]
  if (intent === 'trade') {
    if (previous < 30) delta -= 1
    else if (previous >= 60) delta += 1
  }
  if (intent === 'greet') {
    const patience =
      typeof profile.personality.patience === 'number' ? profile.personality.patience : 0.5
    if (patience < 0.3) delta = 0
  }
  return delta
}

function clampInt(raw: unknown, min: number, max: number, fallback: number): number {
  const n = typeof raw === 'string' ? Number.parseInt(raw, 10) : NaN
  if (!Number.isFinite(n)) return fallback
  return Math.max(min, Math.min(max, n))
}

export const _SUPPORTED_INTENTS = INTERACT_INTENTS
