// NPC interaction router. Endpoints here are per-user and require auth.
//
//   POST /api/npc/:npcId/interact   submit a free-text dialog message,
//                                   get the NPC's reply line for *this*
//                                   player. Reply is generated by the
//                                   Gemini key pool when keys exist; on
//                                   any AI failure we fall back to the
//                                   static dialog library so the world
//                                   stays playable.
//
//   POST /api/npc/:npcId/dialog-hold
//                                   mark this NPC as currently held by an
//                                   authenticated player dialog.
//
//   GET  /api/npc/:npcId/history    list this player's recent dialog
//                                   turns with the given NPC.
//
// Dialog transcript rows are private per-user state. When dialog needs to
// affect public world presence, it must go through SimulationRuntime and a
// persisted FACT_SET event rather than a renderer-only lock.

import { Router, type Request, type Response } from 'express'
import type { SimulationRuntime } from '../sim/runtime.js'
import { requireAuth, toPublicAccount, type AuthConfig } from './auth.js'
import type { AccountStore } from './accounts.js'
import {
  RELATIONSHIP_MAX,
  RELATIONSHIP_MIN,
  type PlayerStateStore,
  clampTrust,
} from './playerState.js'
import {
  INTERACT_INTENTS,
  isInteractIntent,
  pickLine,
  tierForRelationship,
  type InteractIntent,
  type RelationshipTier,
} from '../npcs/dialog.js'
import { generateAiReply, AiDialogError, type AiDialogContext, type PlantContextRow, type RelationshipContextRow } from '../npcs/aiDialog.js'
import { getPlantSpecies } from '../ecosystem/plantSpecies.js'
import { GeminiUnavailableError } from '../npcs/geminiClient.js'
import { isOpenCodeConfigured } from '../npcs/openCodeClient.js'
import { generateWithProviders, AiUnavailableError } from '../npcs/aiProvider.js'
import { makeLivingWorldCommand } from '../kernel/livingWorldCommands.js'
import {
  deriveDynamicGreetLine,
  derivePersonalityGreetLine,
  type LocalizedLine,
} from '../npcs/greetLine.js'
import type { NpcProfile } from '../npcs/types.js'
import type { SettingsStore } from './settings.js'
import { TICKS_PER_HOUR, TICKS_PER_DAY } from '../config/world.js'

const HISTORY_DEFAULT_LIMIT = 20
const HISTORY_MAX_LIMIT = 100
const PLAYER_MESSAGE_MAX_CHARS = 800

// greet 冷卻：每位玩家對每個 NPC 在這個 tick 視窗內最多 +1，避免連點 quick intent 灌好感
const GREET_COOLDOWN_TICKS = TICKS_PER_HOUR
// AI trust-delta clamp constants kept for backward reference only;
// AI's trustDelta is no longer applied (see §9 of ARCHITECTURE.md).
// AI 回傳的 trustDelta 在 server side 再 clamp 一次：上界 +2，避免 AI 隨意給 +3
const AI_TRUST_DELTA_MAX = 2
const AI_TRUST_DELTA_MIN = -5

type ReplySource = 'ai' | 'fallback'

export function createNpcRouter(input: {
  runtime: SimulationRuntime
  store: PlayerStateStore
  settings: SettingsStore
  accounts: AccountStore
  authConfig: AuthConfig
}): Router {
  const router = Router()
  const auth = requireAuth(input.authConfig)

  router.post('/npc/:npcId/dialog-hold', auth, (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND', message: `Unknown NPC id: ${npcId}` })
      return
    }
    const hold = input.runtime.holdNpcForPlayerDialog(String(claims.sub), npcId)
    res.json({
      npcId,
      held: hold !== null,
      tick: hold?.tick ?? input.runtime.getCurrentTick(),
      expiresAtTick: hold?.expiresAtTick ?? null,
    })
  })

  router.post('/npc/:npcId/interact', auth, async (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND', message: `Unknown NPC id: ${npcId}` })
      return
    }
    const body = (req.body ?? {}) as { message?: unknown; intent?: unknown }
    const message = readMessage(body.message)
    const explicitIntent = isInteractIntent(body.intent) ? body.intent : null
    if (!message && !explicitIntent) {
      res.status(400).json({
        error: 'EMPTY_INPUT',
        message: '請輸入要對 NPC 說的話（或選擇一個動作）。',
      })
      return
    }
    if (message && message.length > PLAYER_MESSAGE_MAX_CHARS) {
      res.status(400).json({
        error: 'MESSAGE_TOO_LONG',
        message: `訊息不可超過 ${PLAYER_MESSAGE_MAX_CHARS} 字。`,
      })
      return
    }

    const tick = input.runtime.getCurrentTick()
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const existing = input.store.getRelation(claims.sub, npcId)
    const previousTrust = existing ? existing.trust : baseTrust
    const previousCount = existing ? existing.interactionCount : 0

    const history = input.store.listPersonalEvents({
      accountId: claims.sub,
      npcId,
      limit: 10,
    })

    const tier: RelationshipTier = tierForRelationship(previousTrust)
    const playerMessage = message ?? fallbackMessageFor(explicitIntent!)
    const player = resolvePlayerIdentity(input.accounts, claims.sub, claims.email)

    let replySource: ReplySource = 'fallback'
    let replyZh = ''
    let replyEn = ''
    let resolvedIntent: InteractIntent = explicitIntent ?? 'ask'
    let aiTrustDelta: number | null = null
    let aiError: string | null = null

    const identityLine = identityReplyFor(profile, playerMessage, player.displayName)
    const hasKeys = input.settings.countActive() > 0 || isOpenCodeConfigured(input.settings)
    if (identityLine) {
      replyZh = identityLine.zh
      replyEn = identityLine.en
      resolvedIntent = 'ask'
    } else if (hasKeys) {
      try {
        const rawRumors = input.runtime.getActiveNpcRumors(npcId)
        const rumorCtx = rawRumors.length > 0
          ? rawRumors.map((r) => ({ topic: r.topic as string, subjectId: r.subjectId, tileId: r.tileId, accuracy: r.accuracy }))
          : undefined

        // Phase 3 §37.1 — grounded world context
        const npcState = input.runtime.getNpcs().find((n) => n.id === npcId)
        const npcTile = npcState?.location ?? profile.defaultLocation
        const allProfiles = input.runtime.getNpcs()

        // known-person graph from interaction memories (cap 10 unique)
        const memoryStore = input.runtime.getNpcMemory()
        const knownNpcIds = new Set<string>()
        if (memoryStore) {
          for (const mem of memoryStore.getRecent(npcId, 50)) {
            if (mem.memoryType === 'interaction') {
              const withNpc = (mem.content as Record<string, unknown>).withNpc
              if (typeof withNpc === 'string' && withNpc !== npcId) knownNpcIds.add(withNpc)
              if (knownNpcIds.size >= 10) break
            }
          }
        }
        const knownPersonNames = knownNpcIds.size > 0
          ? [...knownNpcIds]
              .map((id) => allProfiles.find((n) => n.id === id)?.name.zh)
              .filter((n): n is string => typeof n === 'string')
          : undefined

        // relationship context — trust + friend/rival type from interaction history (cap 10)
        const npcRelationshipsStore = input.runtime.getNpcRelationships()
        const relationshipContext: readonly RelationshipContextRow[] | undefined = (() => {
          if (!npcRelationshipsStore) return undefined
          const rows = npcRelationshipsStore.listFor(npcId).slice(0, 10)
          if (rows.length === 0) return undefined
          return rows
            .map((row): RelationshipContextRow | null => {
              const otherId = row.npcA === npcId ? row.npcB : row.npcA
              const nameZh = allProfiles.find((n) => n.id === otherId)?.name.zh
              if (!nameZh) return null
              return { nameZh, trust: row.trust, type: row.relationshipType, interactionCount: row.interactionCount }
            })
            .filter((r): r is RelationshipContextRow => r !== null)
        })()

        // ecology context
        const ecologyRows = input.runtime.getAnimalPopulationOnTile(npcTile)
        const fisheryRow = input.runtime.getFisheryDensityOnTile(npcTile)
        const rawPlantNodes = input.runtime.getBioNodesOnTile(npcTile)
        const plantContext: readonly PlantContextRow[] = rawPlantNodes
          .filter((n) => n.density > 0 && n.capacity > 0)
          .map((n) => ({
            speciesId: n.speciesId,
            nameZh: getPlantSpecies(n.speciesId)?.nameZh ?? n.speciesId,
            saturationPct: Math.min(100, (n.density / n.capacity) * 100),
          }))
        const extinctionWarnings = input.runtime.getExtinctionWarningsOnTile(npcTile)
        const tilePollutionLevel = input.runtime.getTilePollutionLevel(npcTile)
        const populationShifts = input.runtime.getRecentPopulationShifts(3 * TICKS_PER_DAY)

        // faction + history grounding (§11.9)
        const dominantFaction = input.runtime.getDominantFactionOnTile(npcTile)
        const rawHistoryArcs = input.runtime.getHistoryArcsOnTile(npcTile)
        const tileHistoryArcs = rawHistoryArcs.length > 0
          ? rawHistoryArcs.map((a) => ({
              arcType: a.arcType,
              narrationZh: a.narrationZh,
              startTick: a.startTick,
              status: a.status,
            }))
          : undefined

        // recent local events (last 20 events, filter by tile, take 5)
        const localEventLines = input.runtime
          .getRecentEvents(20)
          .filter((ev) => {
            const d = (ev.payload as Record<string, unknown>)
            const data = d.data as Record<string, unknown> | undefined
            return data?.tileId === npcTile
          })
          .slice(0, 5)
          .map((ev) => `[tick ${ev.tick}] ${ev.eventType}`)
        const recentLocalEvents = localEventLines.length > 0 ? localEventLines : undefined

        const rawSkills = input.runtime.getNpcSkills(npcId)
        const skillLevels = rawSkills.length > 0
          ? rawSkills.map((s) => ({ skillId: s.skillId, level: s.level }))
          : undefined

        const beliefCtx = input.runtime.getFormattedBeliefContext(npcId) || undefined
        const reflectionCtx = input.runtime.getFormattedReflectionContext(npcId) || undefined
        const memoryCtx = input.runtime.getFormattedMemoryContext(npcId) || undefined

        const dialogCtx: AiDialogContext = {
          profile,
          player,
          trust: previousTrust,
          tier,
          history,
          playerMessage,
          worldTick: tick,
          worldValidNpcNames: allProfiles.map((npc) => npc.name.zh),
          ...(rumorCtx ? { activeRumors: rumorCtx } : {}),
          ...(knownPersonNames ? { knownPersonNames } : {}),
          ...(relationshipContext ? { relationshipContext } : {}),
          ...(ecologyRows.length > 0 ? { ecologyContext: ecologyRows } : {}),
          ...(fisheryRow ? { fisheryContext: fisheryRow } : {}),
          ...(extinctionWarnings.length > 0 ? { extinctionWarnings } : {}),
          ...(populationShifts.length > 0 ? { recentPopulationShifts: populationShifts } : {}),
          ...(tilePollutionLevel > 0 ? { pollutionLevel: tilePollutionLevel } : {}),
          ...(plantContext.length > 0 ? { plantContext } : {}),
          ...(dominantFaction ? { dominantFaction } : {}),
          ...(tileHistoryArcs ? { tileHistoryArcs } : {}),
          ...(recentLocalEvents ? { recentLocalEvents } : {}),
          ...(skillLevels ? { skillLevels } : {}),
          ...(beliefCtx ? { beliefContext: beliefCtx } : {}),
          ...(reflectionCtx ? { reflectionContext: reflectionCtx } : {}),
          ...(memoryCtx ? { memoryContext: memoryCtx } : {}),
        }
        const ai = await generateAiReply(input.settings, dialogCtx)
        const sanitized = sanitizeNpcReplyForUnknownEntities({
          playerMessage,
          replyZh: ai.zh,
          replyEn: ai.en,
          knownNpcNames: allProfiles.map((npc) => npc.name.zh),
        })
        replyZh = sanitized.zh
        replyEn = sanitized.en
        resolvedIntent = explicitIntent ?? ai.intent
        aiTrustDelta = ai.trustDelta
        replySource = 'ai'
      } catch (err) {
        aiError = err instanceof AiDialogError ? err.message : String(err)
        console.warn('[npc] AI dialog failed, using fallback', aiError)
      }
    }

    if (!identityLine && replySource === 'fallback') {
      const intent = resolvedIntent
      const rotationSeed = tick + Math.floor(previousTrust) + previousCount
      const line = pickLine(npcId, intent, tier, rotationSeed)
      replyZh = line.zh
      replyEn = line.en
    }
    // Per ARCHITECTURE.md §9 — AI is read-only and MAY suggest a
    // trustDelta, but the canonical delta MUST come from a server
    // deterministic rule. We discard the AI value and recompute via
    // staticTrustDelta on every path (AI or fallback).
    aiTrustDelta = staticTrustDelta(resolvedIntent, previousTrust, profile, {
      tick,
      lastInteractionTick: existing?.lastInteractionTick ?? 0,
      interactionCount: previousCount,
    })

    const trustAfter = clampTrust(previousTrust + (aiTrustDelta ?? 0))
    const newTier = tierForRelationship(trustAfter)

    const relation = input.store.upsertRelation({
      accountId: claims.sub,
      npcId,
      trust: trustAfter,
      interactionCount: previousCount + 1,
      lastInteractionTick: tick,
    })

    const personalEvent = input.store.appendPersonalEvent({
      accountId: claims.sub,
      npcId,
      intent: resolvedIntent,
      playerMessage,
      lineZh: replyZh,
      lineEn: replyEn,
      tick,
      trustAfter: relation.trust,
    })
    input.runtime.getNpcMemory?.()?.rememberPlayerDialog({
      npcId,
      playerAccountId: String(claims.sub),
      intent: resolvedIntent,
      playerMessage,
      replyZh,
      replyEn,
      tick,
      trustAfter: relation.trust,
    })

    res.json({
      npcId,
      intent: resolvedIntent,
      tick,
      line: { zh: replyZh, en: replyEn },
      replySource,
      aiError: replySource === 'fallback' ? aiError : null,
      relationship: {
        trust: relation.trust,
        previousTrust,
        delta: relation.trust - previousTrust,
        tier: newTier,
        interactionCount: relation.interactionCount,
        min: RELATIONSHIP_MIN,
        max: RELATIONSHIP_MAX,
      },
      personalEvent: {
        id: personalEvent.id,
        occurredAt: new Date(personalEvent.occurredAt).toISOString(),
        intent: personalEvent.intent,
      },
    })
  })

  // v0.14.0：玩家介入 NPC 爭執。
  //
  // body: {
  //   npcA, npcB,
  //   mode?: 'mediate' | 'provoke' | 'watch' | 'threaten'  -- 直接傳 mode 等同罐頭按鈕
  //   message?: string                                       -- 玩家自由輸入；後端用 AI 分類成 mode
  // }
  // 至少要傳 mode 或 message 之一。如果兩個都傳，**message 優先 + AI 分類覆蓋 mode**。
  //
  // 嚴格遵守 ARCHITECTURE.md §1.1（命令-事件分離）+ §9（AI read-only）：
  //   1. 收到 player input
  //   2. 如果有 message：呼 Gemini 分類意圖（mediate / provoke / watch / threaten）
  //      → AI 回的 intentClass 只是「決策」進命令 payload，AI 不直接寫 EventLog
  //   3. Build PLAYER_INTERVENE typed Command
  //   4. runtime.submitLivingWorldCommand → LivingWorldRuleEngine.evaluate → typed Event 進 EventLog
  //   5. 對 PlayerStateStore 套 mood / trust 副作用（這部分還沒收進 reducer projection；
  //      reducer 只記 EventLog 的 macro 事件，per-player 細節仍在 player_npc_relations 表 — 與
  //      現有 dialog endpoint 行為一致）
  router.post('/npc/intervene', auth, async (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const body = (req.body ?? {}) as {
      npcA?: unknown
      npcB?: unknown
      mode?: unknown
      message?: unknown
    }
    const npcA = typeof body.npcA === 'string' ? body.npcA : null
    const npcB = typeof body.npcB === 'string' ? body.npcB : null
    const explicitMode =
      body.mode === 'mediate' ||
      body.mode === 'provoke' ||
      body.mode === 'watch' ||
      body.mode === 'threaten'
        ? body.mode
        : null
    const message = typeof body.message === 'string' ? body.message.trim() : ''

    if (!npcA || !npcB || npcA === npcB) {
      res.status(400).json({
        error: 'INVALID_INPUT',
        message: 'npcA / npcB 必填且不同。',
      })
      return
    }
    if (!explicitMode && message.length === 0) {
      res.status(400).json({
        error: 'INVALID_INPUT',
        message: 'mode 或 message 至少要傳一個。',
      })
      return
    }
    if (message.length > PLAYER_MESSAGE_MAX_CHARS) {
      res.status(400).json({
        error: 'MESSAGE_TOO_LONG',
        message: `message 不可超過 ${PLAYER_MESSAGE_MAX_CHARS} 字。`,
      })
      return
    }

    const profileA = input.runtime.findProfile(npcA)
    const profileB = input.runtime.findProfile(npcB)
    if (!profileA || !profileB) {
      res.status(404).json({ error: 'NPC_NOT_FOUND' })
      return
    }
    const npcs = input.runtime.getNpcs()
    const npcAState = npcs.find((n) => n.id === npcA)
    const npcBState = npcs.find((n) => n.id === npcB)
    if (!npcAState || !npcBState) {
      res.status(404).json({ error: 'NPC_NOT_FOUND' })
      return
    }
    if (npcAState.location !== npcBState.location) {
      res.status(400).json({
        error: 'NPC_NOT_ON_SAME_TILE',
        message: '兩位 NPC 不在同一區，玩家無法同時介入。',
      })
      return
    }
    if (
      input.runtime.getNpcBuildingId(npcA) !== null ||
      input.runtime.getNpcBuildingId(npcB) !== null
    ) {
      res.status(400).json({
        error: 'NPC_INSIDE_BUILDING',
        message: '至少一位 NPC 在建築內，等他們出來再介入。',
      })
      return
    }

    // ---- 步驟 2：意圖分類 ----
    // message 存在 → 用 AI 分類；沒 message → 直接吃 explicitMode
    let intentClass: 'mediate' | 'provoke' | 'watch' | 'threaten' = explicitMode ?? 'watch'
    let aiClassifyError: string | null = null
    if (message.length > 0 && (input.settings.countActive() > 0 || isOpenCodeConfigured(input.settings))) {
      try {
        intentClass = await classifyInterventionIntent(input.settings, {
          message,
          npcAName: profileA.name.zh,
          npcBName: profileB.name.zh,
        })
      } catch (err) {
        aiClassifyError = err instanceof Error ? err.message : String(err)
        // AI 失敗 → fallback 到 explicitMode（如果有）或 watch
        intentClass = explicitMode ?? 'watch'
        console.warn('[npc] intervene intent classify failed', aiClassifyError)
      }
    } else if (message.length > 0 && !explicitMode) {
      // 有 message 但 AI 沒 key 也沒 explicitMode → 保守當 watch
      intentClass = 'watch'
    }

    const tick = input.runtime.getCurrentTick()
    const tile = npcAState.location

    // 敘事：根據意圖 + 玩家原文寫一行
    const narration = composeInterventionNarration(
      intentClass,
      profileA.name.zh,
      profileB.name.zh,
      message
    )

    // ---- 步驟 3：build PLAYER_INTERVENE Command ----
    const submittedAt = Date.now()
    const command = makeLivingWorldCommand(
      'PLAYER_INTERVENE',
      String(claims.sub),
      'player',
      tick,
      submittedAt,
      {
        playerAccountId: String(claims.sub),
        npcA,
        npcB,
        tile,
        intentClass,
        message,
        narration,
      }
    )

    // ---- 步驟 4：Rule Engine 驗證 + 寫 EventLog ----
    const event = input.runtime.submitLivingWorldCommand(command)
    if (!event) {
      res.status(500).json({ error: 'RULE_ENGINE_REJECTED' })
      return
    }

    // ---- 步驟 5：套 PlayerStateStore 副作用（trust + personal_event） ----
    const baseTrust = (profile: { personality: Readonly<Record<string, number | string>> }) =>
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const relA = input.store.getRelation(claims.sub, npcA)
    const relB = input.store.getRelation(claims.sub, npcB)
    const trustA = relA ? relA.trust : baseTrust(profileA)
    const trustB = relB ? relB.trust : baseTrust(profileB)
    const countA = relA ? relA.interactionCount : 0
    const countB = relB ? relB.interactionCount : 0

    let trustDeltaA = 0
    let trustDeltaB = 0
    let moodDelta = 0
    if (intentClass === 'mediate') {
      trustDeltaA = 2
      trustDeltaB = 2
      moodDelta = 2
    } else if (intentClass === 'provoke') {
      const provokedIsA = npcAState.mood <= npcBState.mood
      trustDeltaA = provokedIsA ? 1 : -3
      trustDeltaB = provokedIsA ? -3 : 1
      moodDelta = -3
    } else if (intentClass === 'threaten') {
      // 威脅：兩位都 mood -5、trust -4。對未成熟的玩家是「真的會掉好感」的選項
      trustDeltaA = -4
      trustDeltaB = -4
      moodDelta = -5
    }

    const newTrustA = clampTrust(trustA + trustDeltaA)
    const newTrustB = clampTrust(trustB + trustDeltaB)

    if (intentClass !== 'watch') {
      input.store.upsertRelation({
        accountId: claims.sub,
        npcId: npcA,
        trust: newTrustA,
        interactionCount: countA + 1,
        lastInteractionTick: tick,
      })
      input.store.upsertRelation({
        accountId: claims.sub,
        npcId: npcB,
        trust: newTrustB,
        interactionCount: countB + 1,
        lastInteractionTick: tick,
      })
    }

    input.store.appendPersonalEvent({
      accountId: claims.sub,
      npcId: npcA,
      intent: 'ask',
      playerMessage: message,
      lineZh: narration,
      lineEn: narration,
      tick,
      trustAfter: newTrustA,
    })
    input.store.appendPersonalEvent({
      accountId: claims.sub,
      npcId: npcB,
      intent: 'ask',
      playerMessage: message,
      lineZh: narration,
      lineEn: narration,
      tick,
      trustAfter: newTrustB,
    })

    res.json({
      ok: true,
      intentClass,
      mode: intentClass,
      message,
      tile,
      eventId: event.eventId,
      sequence: event.sequence,
      classifiedByAi: message.length > 0 && aiClassifyError === null && (input.settings.countActive() > 0 || isOpenCodeConfigured(input.settings)),
      aiClassifyError,
      narration,
      effects: {
        npcA: {
          npcId: npcA,
          trust: newTrustA,
          trustDelta: trustDeltaA,
          moodDelta,
        },
        npcB: {
          npcId: npcB,
          trust: newTrustB,
          trustDelta: trustDeltaB,
          moodDelta,
        },
      },
    })
  })

  router.get('/npc/:npcId/greet', auth, (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND' })
      return
    }
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const relation = input.store.getRelation(claims.sub, npcId)
    const trust = relation ? relation.trust : baseTrust
    const interactionCount = relation ? relation.interactionCount : 0
    const lastInteractionTick = relation ? relation.lastInteractionTick : 0
    const currentTick = input.runtime.getCurrentTick()
    // Avoid circular import: dynamic import deferred greet helper.
    // Use the runtime-already-imported derivePersonalityGreetLine + the new
    // deriveDynamicGreetLine via require-style lazy load.
    // 因為 module 已經 import 過 makeLivingWorldCommand，這個檔靜態 import 沒問題。
    // 直接 inline import：
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    res.json({
      npcId,
      greetLine: deriveGreetWithFallback(profile, {
        trust,
        interactionCount,
        lastInteractionTick,
        currentTick,
      }),
      relationship: {
        trust,
        tier: tierForRelationship(trust),
        interactionCount,
        lastInteractionTick,
        seeded: relation === null,
      },
    })
  })

  router.get('/npc/:npcId/history', auth, (req: Request, res: Response) => {
    const claims = req.auth
    if (!claims) {
      res.status(401).json({ error: 'UNAUTHORIZED' })
      return
    }
    const npcId = String(req.params.npcId ?? '')
    const profile = input.runtime.findProfile(npcId)
    if (!profile) {
      res.status(404).json({ error: 'NPC_NOT_FOUND' })
      return
    }
    const limit = clampInt(req.query.limit, 1, HISTORY_MAX_LIMIT, HISTORY_DEFAULT_LIMIT)
    const rows = input.store.listPersonalEvents({
      accountId: claims.sub,
      npcId,
      limit,
    })
    const relation = input.store.getRelation(claims.sub, npcId)
    const baseTrust =
      typeof profile.personality.trustBase === 'number'
        ? clampTrust(profile.personality.trustBase)
        : 50
    const trust = relation ? relation.trust : baseTrust
    res.json({
      npcId,
      relationship: {
        trust,
        tier: tierForRelationship(trust),
        interactionCount: relation ? relation.interactionCount : 0,
        lastInteractionTick: relation ? relation.lastInteractionTick : 0,
        min: RELATIONSHIP_MIN,
        max: RELATIONSHIP_MAX,
        seeded: relation === null,
      },
      events: rows.map((row) => ({
        id: row.id,
        intent: row.intent,
        playerMessage: row.playerMessage,
        line: { zh: row.lineZh, en: row.lineEn },
        tick: row.tick,
        occurredAt: new Date(row.occurredAt).toISOString(),
        trustAfter: row.trustAfter,
      })),
    })
  })

  return router
}

function deriveGreetWithFallback(
  profile: NpcProfile,
  ctx: {
    trust: number
    interactionCount: number
    lastInteractionTick: number
    currentTick: number
  }
): LocalizedLine {
  try {
    return deriveDynamicGreetLine(profile, ctx)
  } catch {
    return derivePersonalityGreetLine(profile)
  }
}

export function sanitizeNpcReplyForUnknownEntities(input: {
  playerMessage: string
  replyZh: string
  replyEn: string
  knownNpcNames: readonly string[]
}): LocalizedLine {
  const unknownTerm = extractUnknownEntityTerm(input.playerMessage, input.knownNpcNames)
  if (!unknownTerm) return { zh: input.replyZh, en: input.replyEn }
  const compactReply = input.replyZh.replace(/\s+/g, '')
  const hallucinatedUnknown =
    compactReply.includes(`哪個${unknownTerm}`) ||
    compactReply.includes(`哪位${unknownTerm}`) ||
    compactReply.includes(`幾個${unknownTerm}`) ||
    compactReply.includes(`幾個「${unknownTerm}」`) ||
    compactReply.includes(`有幾個「${unknownTerm}」`) ||
    compactReply.includes(`有幾個${unknownTerm}`) ||
    compactReply.includes(`知道${unknownTerm}`) ||
    compactReply.includes(`認識${unknownTerm}`) ||
    compactReply.includes(`${unknownTerm}是`) ||
    compactReply.includes(`${unknownTerm}在`) ||
    compactReply.includes(`${unknownTerm}住`) ||
    compactReply.includes(`${unknownTerm}屬於`) ||
    compactReply.includes(`${unknownTerm}跟`)
  if (!hallucinatedUnknown) return { zh: input.replyZh, en: input.replyEn }
  return {
    zh: `「${unknownTerm}？我不認得這個稱呼。你是在說誰，還是在罵人？」`,
    en: `"${unknownTerm}? I do not recognize that name. Who are you talking about, or are you insulting someone?"`,
  }
}

function extractUnknownEntityTerm(message: string, knownNpcNames: readonly string[]): string | null {
  const normalizedKnown = new Set(knownNpcNames.map((name) => name.trim()).filter(Boolean))
  const compact = message.replace(/\s+/g, '')
  const patterns = [
    /^(.{2,8})就是/,
    /^(.{2,8})(?:是誰|是谁|在哪|住哪)/,
    /認識(.{2,8})(?:嗎|吗|\?|？)?$/,
    /知道(.{2,8})(?:嗎|吗|\?|？)?$/,
    /「(.{2,8})」/,
    /『(.{2,8})』/
  ]
  for (const pattern of patterns) {
    const match = compact.match(pattern)
    const term = match?.[1]?.trim().replace(/[嗎吗?？]+$/u, '')
    if (!term || normalizedKnown.has(term)) continue
    if (/^[\p{Script=Han}\p{Letter}\p{Number}_-]{2,8}$/u.test(term)) return term
  }
  return null
}

function resolvePlayerIdentity(
  accounts: AccountStore,
  accountId: number,
  email: string
): { accountId: number; displayName: string; email: string } {
  const account = accounts.findById(accountId)
  const displayName = account
    ? toPublicAccount(account).displayName
    : email.split('@')[0] ?? `玩家 #${accountId}`
  return { accountId, displayName, email }
}

function identityReplyFor(
  profile: NpcProfile,
  playerMessage: string,
  playerDisplayName: string
): LocalizedLine | null {
  const normalized = playerMessage.replace(/\s+/g, '')
  const asksPlayerIdentity =
    normalized.includes('我是誰') ||
    normalized.includes('我是谁') ||
    normalized.includes('我叫什麼') ||
    normalized.includes('我叫什么') ||
    normalized.includes('你知道我是誰') ||
    normalized.includes('你知道我是谁')
  const asksNpcIdentity =
    normalized.includes('你是誰') ||
    normalized.includes('你是谁') ||
    normalized.includes('你叫什麼') ||
    normalized.includes('你叫什么')

  if (!asksPlayerIdentity && !asksNpcIdentity) return null

  const npcZh = profile.name.zh
  const npcEn = profile.name.en
  const roleZh = profile.role.zh
  const roleEn = profile.role.en

  if (asksPlayerIdentity && asksNpcIdentity) {
    return {
      zh: `「我是${npcZh}，${roleZh}。你是${playerDisplayName}，我記得。」`,
      en: `"I am ${npcEn}, ${roleEn}. You are ${playerDisplayName}; I remember."`,
    }
  }
  if (asksPlayerIdentity) {
    return {
      zh: `「你是${playerDisplayName}。這名字我記著，不用再考我。」`,
      en: `"You are ${playerDisplayName}. I remember the name; no need to test me again."`,
    }
  }
  return {
    zh: `「我是${npcZh}，${roleZh}。你要問事就直接問。」`,
    en: `"I am ${npcEn}, ${roleEn}. Ask plainly if you need something."`,
  }
}

function readMessage(raw: unknown): string | null {
  if (typeof raw !== 'string') return null
  const trimmed = raw.trim()
  return trimmed.length > 0 ? trimmed : null
}

function fallbackMessageFor(intent: InteractIntent): string {
  switch (intent) {
    case 'greet':
      return '（玩家走上前打招呼。）'
    case 'ask':
      return '（玩家想探聽近況。）'
    case 'trade':
      return '（玩家提議一筆交易。）'
    case 'leave':
      return '（玩家準備告辭。）'
  }
}

function staticTrustDelta(
  intent: InteractIntent,
  previous: number,
  profile: { personality: Readonly<Record<string, number | string>> },
  ctx: { tick: number; lastInteractionTick: number; interactionCount: number }
): number {
  // greet 在 fallback 路徑加 cooldown：每位 NPC 每 GREET_COOLDOWN_TICKS 內最多 +1
  if (intent === 'greet') {
    const sinceLast = ctx.tick - ctx.lastInteractionTick
    const isFirstEver = ctx.interactionCount === 0
    const cooldownPassed = sinceLast >= GREET_COOLDOWN_TICKS
    if (!isFirstEver && !cooldownPassed) return 0
    const patience =
      typeof profile.personality.patience === 'number' ? profile.personality.patience : 0.5
    if (patience < 0.3) return 0
    return 1
  }
  // ask / trade 在 fallback 路徑（沒有實際資訊或物品交換）回 0；
  // 之後 trade 接到實際物品交換時，再用 trade 撮合結果額外加分
  if (intent === 'trade' && previous < 30) return -1
  return 0
}

// `serverClampAiDelta` was removed in v0.11.0 — per ARCHITECTURE.md §9
// AI is advisory only and the canonical trust delta comes from
// `staticTrustDelta` regardless of whether the line was AI-rendered or
// from the fallback library. The constants AI_TRUST_DELTA_MAX/MIN are
// kept above so older modules importing them keep compiling, but the
// runtime no longer references them.
void AI_TRUST_DELTA_MAX
void AI_TRUST_DELTA_MIN

function clampInt(raw: unknown, min: number, max: number, fallback: number): number {
  const n = typeof raw === 'string' ? Number.parseInt(raw, 10) : NaN
  if (!Number.isFinite(n)) return fallback
  return Math.max(min, Math.min(max, n))
}

export const _SUPPORTED_INTENTS = INTERACT_INTENTS

/**
 * v0.14.0：用 Gemini 把玩家對 NPC 爭執說的一句話分類成四個 intent 類別之一。
 * AI 回傳必須是純小寫單字 mediate / provoke / watch / threaten。任何其它字
 * (例如「我不知道」/ Markdown / JSON) 一律視為失敗，由 caller fallback。
 *
 * AI read-only：分類結果只進命令 payload，不直接寫 EventLog。
 */
async function classifyInterventionIntent(
  store: SettingsStore,
  ctx: { message: string; npcAName: string; npcBName: string }
): Promise<'mediate' | 'provoke' | 'watch' | 'threaten'> {
  const systemPrompt = [
    '你是一位場景觀察員。場面：兩位 NPC 正在爭執，玩家此刻插話。',
    '你的任務是把玩家說的那句話分類成下列四個動作之一：',
    '- mediate：嘗試調解、勸架、緩和情緒、把雙方拉開',
    '- provoke：火上加油、煽動、起鬨、選邊站、貶低其中一方',
    '- threaten：直接威脅暴力 / 報復、命令對方住口、給最後通牒',
    '- watch：站在旁邊看、純粹評論不選邊、表達中立、沒有實質行動',
    '',
    '⚠️ 鐵則：',
    '1. 你只回一個小寫英文單字：mediate / provoke / watch / threaten。',
    '2. 不要寫 JSON、不要寫 Markdown、不要寫解釋。',
    '3. 含糊不清就回 watch。',
    '4. 玩家用詞激烈但中立（例如只是 commentary）→ watch；玩家威脅 → threaten。',
  ].join('\n')
  const userPrompt = [
    `現場兩位 NPC：${ctx.npcAName} 與 ${ctx.npcBName}（正在爭執）`,
    `玩家剛剛說：「${ctx.message}」`,
    '',
    '玩家的動作分類是？',
  ].join('\n')

  let raw: string
  try {
    const result = await generateWithProviders(store, {
      systemPrompt,
      userPrompt,
      temperature: 0.2,
      maxOutputTokens: 32,
      // 純分類任務：關 thinking、關 JSON mode
      thinkingBudget: 0,
    })
    raw = result.text
  } catch (err) {
    if (err instanceof GeminiUnavailableError || err instanceof AiUnavailableError) {
      throw new Error(`AI 不可用：${err.message}`)
    }
    throw err
  }
  const norm = raw.trim().toLowerCase().replace(/[^a-z]/g, '')
  if (norm === 'mediate' || norm === 'provoke' || norm === 'watch' || norm === 'threaten') {
    return norm
  }
  // 寬鬆 fallback：raw 包含某個關鍵字
  if (norm.includes('mediate')) return 'mediate'
  if (norm.includes('provoke')) return 'provoke'
  if (norm.includes('threaten')) return 'threaten'
  if (norm.includes('watch')) return 'watch'
  throw new Error(`Unrecognized intent class: "${raw.slice(0, 60)}"`)
}

function composeInterventionNarration(
  intent: 'mediate' | 'provoke' | 'watch' | 'threaten',
  npcAName: string,
  npcBName: string,
  message: string
): string {
  const messageSnippet = message.length > 0 ? `（玩家說：「${trim80(message)}」）` : ''
  switch (intent) {
    case 'mediate':
      return `你站到${npcAName}和${npcBName}中間，把火氣壓下來。${messageSnippet}`
    case 'provoke':
      return `你火上加油，雙方更不肯讓步。${messageSnippet}`
    case 'threaten':
      return `你發出威脅，${npcAName}和${npcBName}都警戒地看著你。${messageSnippet}`
    case 'watch':
    default:
      return `你站在一旁看著，沒插嘴。${messageSnippet}`
  }
}

function trim80(s: string): string {
  if (s.length <= 80) return s
  return s.slice(0, 80) + '…'
}
